const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_USER_DATA: "STORE_USER_DATA",
   STORE_DATE_REQUESTS: "STORE_DATE_REQUESTS",
   UPDATE_MATCH: "UPDATE_INDEX_OF_CURRENT_CARD",
};

export default actions;
